const allBooks = document.getElementById('allListBooks')
const bestSeller = document.createElement('h2')
allBooks.appendChild(bestSeller)
const text = document.createTextNode('Prueba')
bestSeller.appendChild(text)
allBooks.append('PRUEBA SEGUIDA', document.createElement('p'))
allBooks.append('PRUEBA DE H2', document.createElement('h2'))
let prueba = allBooks.appendChild(document.createElement('div'))
console.log(prueba)
prueba.setAttribute("id", "listBooks")
